### ISSUE TITLE
No data from second MJ_HT_LY temp sensor

### ISSUE THREAD

**Issue by waiet** [shaarkys/MiTempHum-Homey#1]
I paired 2 sensors Xiaomi MJ_HT_LY.
But always homey has data only from 1 sensor. I tried to pair it few times, still with same result.

![Screenshot_20240716_203708_Homey](https://github.com/user-attachments/assets/843bcff8-ad57-48a8-8a38-8a5aad10de04)

Homey diagnostics report id:
0c3a9d67-2ae1-4792-92a5-544a235866e7

**Comment by shaarkys** [comment]
Apologies, seems that GitHUB has not notified me about this issue, can you create the log once more and let me know?

Also if you can share screenshots from https://tools.developer.homey.app/tools/ble highlighting those two sensors based on their MAC addresses. Thank you.

**Comment by shaarkys** [comment]
Feel free to reopen this issue if you will be able to provide details.
