### ISSUE TITLE
LYWSD03MMC original firmware

### ISSUE THREAD

**Issue by edsallo** [shaarkys/MiTempHum-Homey#2]
On Homey Pro (2019) the sensors (round) LYWSD03MMC worked perfectly with the original firmware with the app that I will attach. Unfortunately, this app does not install on Homey Pro 2013. I hope you will add the ability to work with the sensors with the original firmware.
[com.maxmudjon.mi_ble.zip](https://github.com/user-attachments/files/17529792/com.maxmudjon.mi_ble.zip)

**Comment by shaarkys** [comment]
What is Homey 2013, I don't recognize that model? Also can you share which error you get? What is the Homey firmware version?

**Comment by edsallo** [comment]
> What is Homey 2013, I don't recognize that model? Also can you share which error you get? What is the Homey firmware version?

Sorry! Of course Homey Pro 2023.)
I just migrated from homey 2019 to 2023.
On Homey 2019, the sensors with this application worked on the original firmware.
The application was created by a friend of mine. He no longer supports this app.

**Comment by edsallo** [comment]
I just wanted to share the best practices of another developer. Perhaps this will help you improve the application.

**Comment by shaarkys** [comment]
Not sure I follow, I'm using this app on Homey 2023. Which error do you get?
