### ISSUE TITLE
Negative temperatures

### ISSUE THREAD

**Issue by Anders-24** [shaarkys/MiTempHum-Homey#3]
Hi!
I have a couple of Xiaomi Mijia and the work very fine with the Homey app. I have one in my car and now when the temperature drops below zero it shows the temp as 65536-(-temp).
![Xiaomi_Homey](https://github.com/user-attachments/assets/f75d5cc0-3d66-43d6-b42a-dd7f3df89e2c)

**Comment by shaarkys** [comment]
I will have a look, can you share diag log ?

**Comment by shaarkys** [comment]
Feel free to reopen this issue if you will be able to provide log.

**Comment by Anders-24** [comment]
Hi,I have sent an diagnostic report. Negative temperatures are shown correct for zigbeeflashed device, but not for ATCHälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  07:03  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Author ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
Feel free to reopen this issue if you will be able to provide log.

**Comment by Anders-24** [comment]
Id for diagnostic reportadf2d5c6-9325-4207-ad79-738de0effa83HälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  07:03  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Author ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
Feel free to reopen this issue if you will be able to provide log.

**Comment by shaarkys** [comment]
Will have a look, thanks !

**Comment by Anders-24** [comment]
Hi, One ATC sensor was brought below zero then none of them (have a few) are updating data. The zigbee one is still updating. Restarted the app, none is updating.Restarted Homey, none is updating.Reinstalled v1.2.19, updating :-)Report id6eff6599-5636-4e1c-9173-c9c2b61181ccHälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  18:14  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Author ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
Can you test latest https://homey.app/en-us/app/hu.corenet.mitemp/Xiaomi-Miija/test and submit log, even if the test will be OK ? In case of any troubles, simply install https://homey.app/en-us/app/hu.corenet.mitemp/Xiaomi-Miija/ (non test)

**Comment by shaarkys** [comment]
I see the problem, will fix that today.

**Comment by Anders-24** [comment]
Great, i am on vacation until wednesday so can do new test on thursday.HälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  20:49  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Author ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
I see the problem, will fix that today.

**Comment by shaarkys** [comment]
Please test as per your availability - https://homey.app/en-us/app/hu.corenet.mitemp/Xiaomi-Miija/test - 1.2.21

**Comment by Anders-24** [comment]
Now all ATC sensors show extreme values, both under and over zero degreesba938d3b-2e56-4837-8ea9-fc0f9ac6af57HälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  21:04  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Author ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
Please test as per your availability - https://homey.app/en-us/app/hu.corenet.mitemp/Xiaomi-Miija/test - 1.2.21

**Comment by shaarkys** [comment]
Please revert at this moment to non-test.

**Comment by shaarkys** [comment]
Try with https://homey.app/a/hu.corenet.mitemp/test/ - 1.2.22, just keep it updating values, it shall again report high values <0C but I added to see buffer from the sensor, to see how to decode it (I don't have any ATC BLE sensor with me and not with <0C). No need to update this thread, just install, run, send debug. Thank you.

**Comment by shaarkys** [comment]
@Anders-24 , last one for today please - 1.2.23 - https://homey.app/a/hu.corenet.mitemp/test/ - also seems none of the sensors were below <0C ? Thank you.

**Comment by Anders-24** [comment]
Looks like it works!3f384240-fb88-4919-8457-b0a4d41a67e4HälsningarAndersSkickat från min Galaxy
-------- Originalmeddelande --------Från: Bretislav Kubesa ***@***.***> Datum: 2024-12-13  22:25  (GMT+01:00) Till: shaarkys/MiTempHum-Homey ***@***.***> Kopia: Anders-24 ***@***.***>, Mention ***@***.***> Ämne: Re: [shaarkys/MiTempHum-Homey] Negative temperatures (Issue #3) 
@Anders-24 , last one for today please - 1.2.23 - https://homey.app/a/hu.corenet.mitemp/test/ - also seems none of the sensors were below <0C ? Thank you.
