### ISSUE TITLE
Battery draining fast

### ISSUE THREAD

**Issue by desmortum** [shaarkys/MiTempHum-Homey#4]
Greetings. Thanks for the great app.

Starting November 1st or so battery of thermometer started reporting that it's drained 1-2 percent a day. Before that, it stayed 100% for a few months.

I have LYWSD03MMC-z with Zigbee firmware which I did not change for a few months.

Is that a bug in the recent app update or is that nature of the battery? Or am I missing something? 

![IMG_0089](https://github.com/user-attachments/assets/fce719f0-37ad-4243-bac0-99b0b64acfd1)

**Comment by shaarkys** [comment]
Zigbee version hasn't been touched for a while (6 months), more over I commented on forum for this - https://community.homey.app/t/app-pro-xiaomi-miija-temperature-and-humidity/78560/121?u=sharkys 

Not sure what is causing it but I observe it among different platforms (eg. Home assistant has nothing to do with this implementation) and same firmware versions - yet they behaves differently.

How the situation looks now and which firmware you are actually using ?

**Comment by desmortum** [comment]
@shaarkys, it continues same way. Sorry, I do not remember firmware I flashed, and I don't have HA, only Homey and I do not know how to get that info from device but I attach a screenshot of info from dev tools below.

<img width="469" alt="Screenshot 2024-11-29 at 11 57 18" src="https://github.com/user-attachments/assets/0c60c8f0-a80c-41ec-ab84-f192a977808e">
![IMG_0092](https://github.com/user-attachments/assets/6b96e307-f6ea-4fc6-9ceb-cbc8a7e0fe30)
![IMG_0093](https://github.com/user-attachments/assets/4c6bf7e0-32ab-4c21-80f3-1779558e6584)

**Comment by desmortum** [comment]
@shaarkys, but I think it was one of https://github.com/pvvx/ATC_MiThermometer ZigBee builds OTA tool recommended. Latest for last month or so.

**Comment by shaarkys** [comment]
This is the firmware version : 
![firmware](https://github.com/user-attachments/assets/6b2e4472-001d-40f0-be9f-d0fad336bb2b)
Unfortunately latest is  : 3001-1100 - https://github.com/devbis/z03mmc/releases/tag/1.1.0 - there is no other way to upgrade it then via Home Assistant, if this is major concern - or maybe someone with HA and Zigbee can help.
